version: '3.8'

services:
  node:
    build:
      context: docker/dev
#    user: node
    working_dir: /node/app
    environment:
       HOST: 0.0.0.0
       PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/node/app
    networks:
      - web
    command: sh -c 'pnpm i && pnpm dev'

networks:
  web:
    external: true
